### ISSUE TITLE
Can't work with Opencv3.2.0

### ISSUE THREAD

**Issue by hjptriplebee** [abhi-kumar/CAR-DETECTION#1]
I complied it with Opencv3.2.0.When I ran the program, I got the following message:

got image
checkcascade : checkcas.xml loaded
cascade : cas1.xml loaded
OpenCV Error: The function/feature is not implemented (HOG cascade is not supported in 3.0) in read, file /home/hjp/opencv/opencv/modules/objdetect/src/cascadedetect.cpp, line 1455
terminate called after throwing an instance of 'cv::Exception' what():  /home/hjp/opencv/opencv/modules/objdetect/src/cascadedetect.cpp:1455: error: (-213) HOG cascade is not supported in 3.0 in function read

I searched the problem. It seems that developers decided to drop the current HOG cascades in OpenCV 3.x. The implemented HOG features are quite weird - different from Dalal's interpretation of HOG, different from P. Dollar integral channel features. In xobjdetect we slowly grow superior ICF/ACF+WaldBoost-based detector, which is there already and will be improved during 2015. 

Available from: https://www.researchgate.net/post/Is_HOG_cascade_classifier_not_supported_in_OpenCV_30 [accessed May 10, 2017].
